-- MySQL Script generated by MySQL Workbench
-- Sat Sep 17 18:40:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `profile_picture` MEDIUMTEXT NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `cover_picture` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`following_followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`following_followers` (
  `following_id` INT NOT NULL,
  `follower_id` INT NOT NULL,
  PRIMARY KEY (`following_id`, `follower_id`),
  INDEX `fk_users_has_users_users1_idx` (`follower_id` ASC) ,
  INDEX `fk_users_has_users_users_idx` (`following_id` ASC) ,
  CONSTRAINT `fk_users_has_users_users`
    FOREIGN KEY (`following_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`follower_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blocked_blockers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blocked_blockers` (
  `blocked_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`blocked_id`, `user_id`),
  INDEX `fk_users_has_users_users3_idx` (`user_id` ASC) ,
  INDEX `fk_users_has_users_users2_idx` (`blocked_id` ASC) ,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`blocked_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users3`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tweets` (
  `tweet_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tweet_text` VARCHAR(280) NOT NULL,
  `tweet_picture` MEDIUMTEXT NULL,
  PRIMARY KEY (`tweet_id`),
  INDEX `fk_tweets_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_tweets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_likes` (
  `user_id` INT NOT NULL,
  `tweet_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `tweet_id`),
  INDEX `fk_users_has_tweets_tweets1_idx` (`tweet_id` ASC) ,
  INDEX `fk_users_has_tweets_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_users_has_tweets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_tweets_tweets1`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `mydb`.`tweets` (`tweet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
